### ISSUE TITLE
Please add a screen shot to the readme

### ISSUE THREAD

**Issue by unixorn** [agentshadow/shadow-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by luisacunat** [comment]
Great! I've updated the Readme and included a screenshot. Thanks for checking it out!

**Comment by unixorn** [comment]
Thanks, adding.
